main: name.sgriffeth.MCGameMaker.Main
name: MC-GameMaker 
version: 1.0
api-version:
author: SGriffeth
description: Facilitates mini game creation
commands:
   action:
      description:
      usage: /action confirm {\yes | \no}
      permission:
   command:
      description:
      usage: /command {configure {Minecraft_command_line | help} | schedule {help} | event {Minecraft_event [clear | list] | help | clear | list}} 
   if:
      description:
      usage:
   gui:
      description:
   tutorial:
      description:
   save:
      description:
   load:
      description: