main: name.griffeth.sebastian.MCGameMaker.Main
name: MC-GameMaker 
version: 1.0
api-version: 1.16
author: Sebastian Griffeth 
description: Create custom mobs with ease in minecraft
commands:
   block:
      description:
   item:
      description:
   mob:
      description:
   command:
      description:
   tutorial:
      description: