main: name.sgriffeth.MCGameMaker.Main
name: MC-GameMaker 
version: 1.0
api-version: 1.16
author: SGriffeth
description: Create custom mobs with ease in minecraft
commands:
   action:
      description:
      usage: /action confirm {\yes | \no}
      permission:
   block:
      description:
   command:
      description:
      usage: /command {configure {Minecraft_command_line | help} | schedule {help} | event {Minecraft_event [clear | list] | help | clear | list}} 
   item:
      description:
   mob:
      description:
   tutorial:
      description:
   save:
      description:
   load:
      description: